GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';

CREATE USER 't_sa'@'%' IDENTIFIED BY 't_sa';

CREATE DATABASE IF NOT EXISTS t_sa;
CREATE DATABASE IF NOT EXISTS t_sa_1;
CREATE DATABASE IF NOT EXISTS t_sa_2;

GRANT ALL PRIVILEGES ON t_sa.* TO 't_sa'@'%';
GRANT ALL PRIVILEGES ON t_sa_1.* TO 't_sa'@'%';
GRANT ALL PRIVILEGES ON t_sa_2.* TO 't_sa'@'%';
